artifacts:
  FACERECOG_MODEL: deepface
  HAARCASCADE_PATH: "models\\haarcascade_frontalface_default.xml"
  INTERMIDEIATE_DIR: "data\\intermediate"
  UPLOADED_ID_CARD_NAME: "uploaded_id_card.jpg"
  FACE_IMG2_NAME: "uploaded_face_image.jpg"
  CONTOUR_FILE: "cropped_id_card.jpg"
  FACE_IMG1_NAME: "extracted_face_image.jpg"
  LOG_FILE_NAME: "logs.log"
  LOG_DIR: "logs"
parameters:
  GAUSSIAN_BLUR_KERNEL_SIZE: 5
  ADAPTIVE_THRESHOLD_BLOCK_SIZE: 11
  ADAPTIVE_THRESHOLD_C: 2
  SCALE_FACTOR: 1.1
  MIN_NEIGHBORS: 5
  INCREASED_SCALE_FACTOR: 1.50
  DEEPFACE_MODEL: "Facenet"